d <- read_csv("../data/intermediate/issues_negative_campaigning_2020.csv")

raw <- d %>%
  select(date, medium, source = from, party = par, text_appeal = appeal,
         issue, direction_appeal = neg) %>%
  mutate(medium = recode(medium, 
                         "fb" = "Facebook", 
                         "np" = "Newspapers", 
                         "ts" = "TV-shows"),
         source = recode(source,
                         "50plus" = "@50Pluspartij",
                         "cda" = "@kiesCDA",
                         "cu" = "@ChristenUnie",
                         "d66" = "@D66",
                         "fvd" = "@forumvoordemocratie",
                         "gl" = "@groenlinks",
                         "max" = "Omroep Max",
                         "pauwjinek" = "Pauw & Jinek",
                         "pvda" = "@PartijvandeArbeid",
                         "pvv" = "@partijvoordevrijheid",
                         "pvdd" = "@PartijvoordeDieren",
                         "sgp" = "@SGPnieuws",
                         "sp" = "@SocialistischePartij",
                         "telegraaf" = "de Telegraaf",
                         "volkskrant" = "de Volkskrant",
                         "vvd" = "@VVD",
                         "wnl" = "WNL op Zondag"),
         party = recode(party,
                        "50plus" = "50PLUS",
                        "cda" = "CDA",
                        "cu" = "CU",
                        "d66" = "D66",
                        "fvd" = "FvD",
                        "gl" = "GL",
                        "pvda" = "PvdA",
                        "pvdd" = "PvdD",
                        "pvv" = "PVV",
                        "sgp" = "SGP",
                        "sp" = "SP",
                        "vvd" = "VVD"),
         cmp_code = recode(party,
                           "50PLUS" = 22953,
                           "CDA" = 22521,
                           "CU" =  22526,
                           "D66" = 22330,
                           "FvD" = 22730,
                           "GL" = 22110,
                           "PvdA" = 22320,
                           "PvdD" = 22951,
                           "PVV" = 22722,
                           "SGP" = 22952,
                           "SP" = 22220,
                           "VVD" = 22420),
         issue = recode(issue,
                        "admin" = "Institutional Reform",
                        "agrar" = "Agriculture",
                        "crime" = "Crime Fighting",
                        "cult" = "Cultural Industry",
                        "defence" = "Military Interventions",
                        "econ" = "Taxes, Budget & Economy",
                        "edu" = "Education",
                        "entrep" = "Entrepreneurship",
                        "environ" = "Environment & Climate",
                        "eu" = "European Union",
                        "foreignaid" = "Foreign Aid",
                        "gov" = "Efficient Government",
                        "health" = "Health Care",
                        "housing" = "Housing",
                        "imm" = "Immigration",
                        "jobs" = "Labour Market",
                        "mobility" = "Mobility Network",
                        "norm" = "Norms and Values",
                        "social" = "Social Security",
                        "terror" = "Counter-Terrorism"),
         direction_appeal = recode(direction_appeal,
                                   `0` = "Positive Appeal",
                                   `1` = "Negative Appeal")) %>%
  select(date, medium, source, party, cmp_code, text_appeal,
         issue, direction_appeal)
write_csv(raw, "../data/raw/coded-data-NL-2017-campaign.csv")


