---
title: 'Analysis'
author: "Dirck de Kleer & Mariken A.C.G. van der Velden"
output: 
  github_document:
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(printr)
library(rmarkdown)
```

# Scripts
- [Required Packages &amp; Reproducibility](#required-packages-&amp;-reproducibility)
- [Analysis](#analysis)
  - [Specifying the Multiverse](#specifiying-the-multiverse)
  - [H1a](#H1a)
  - [H1b](#H1b)
  - [H2a](#H2a)
  - [H2b](#H2b)
  
## Required Packages &amp; Reproducibility
```{r, message=FALSE, warning=F}
rm(list=ls())

source("../lib/functions.R")
```

## Analysis
```{r "data for analyses"}
load("../data/intermediate/cleaned_data.RData")
df <- d %>%
  mutate(negative_appeal = ifelse(direction_appeal=="Negative Appeal",
                                  1,0)) %>%
  group_by(party, date) %>%
  summarise(negative_appeals = n(),
            polls1 = mean(poll_standing1, na.rm = T),
            polls2 = mean(poll_standing2, na.rm = T),
            polls3 = mean(poll_standing3, na.rm = T),
            polls4 = mean(poll_standing4, na.rm = T),
            polls5 = mean(poll_standing5, na.rm = T),
            polls6 = mean(poll_standing6, na.rm = T),
            polls7 = mean(poll_standing7, na.rm = T),
            polls8 = mean(poll_standing8, na.rm = T),
            polls9 = mean(poll_standing9, na.rm = T),
            io1 = mean(aio_percentage, na.rm = T),
            io2 = mean(cio_mean, na.rm = T),
            io3 = mean(cio_median, na.rm = T),
            io4 = mean(cio_sd, na.rm = T),
            ie1 = mean(ie_median_ches2017, na.rm = T),
            ie2 = mean(ie_mean_ches2017, na.rm = T),
            ie3 = mean(ie_median_ches2014, na.rm = T),
            ie4 = mean(ie_mean_ches2014, na.rm = T),
            ie5 = mean(ie_median_cmp2017, na.rm = T),
            ie6 = mean(ie_mean_cmp2017, na.rm = T),
            ie7 = mean(ie_median_cmp2012, na.rm = T),
            ie8 = mean(ie_mean_cmp2012, na.rm = T),
            ji1  = mean(journalistic_intervenience, na.rm = T),
            ji2 = sum(journalistic_intervenience),
            ji3 = ji2-ji1
            ) %>%
  mutate(opposition = ifelse(party == "VVD", 0,
                      ifelse(party == "PvdA", 0, 1)),
         new_party = ifelse(party == "FvD", 1, 0),
         ie3 = ifelse(party == "FvD", 0, ie3),
         ie4 = ifelse(party == "FvD", 0, ie4),
         ie7 = ifelse(party == "FvD", 0, ie7),
         ie8 = ifelse(party == "FvD", 0, ie8)
         ) %>%
  ungroup()

df <- slide(data = df, Var = "negative_appeals", TimeVar = "date",
               GroupVar = "party", NewVar = "l_negative_appeal", 
            slideBy = -1)
```

## Gesrpek kasper: glmer neg_appeals = ldv + rest: possion of neg.bin

```{r "h1"}
h1 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("ji1", "ji2", "ji3"),
                      controls = c("polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9",
                                  "ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8",
                                  "io1","io2","io3","io4"),
                      model = "glmer_mv")

results %>%  
  mutate(id = 1:69,
         x = recode(x, 
                    `ji1` = "Daily Average of Journalistic Intervention",
                    `ji2` = "Sum of Daily Journalistic Intervention",
                    `ji3` = "Deviation from Daily Average Journalistic Intervention")) %>%
  ggplot(aes(x = reorder(id, estimate),
             y = estimate,
             group = id,
             colour = x,
             ymin = conf.low,
             ymax = conf.high)) +
  geom_point() + geom_errorbar() +
  theme_minimal() +
  labs(x = "", y = "Estimate",
       title = "Effect of Journalistic Intervenience on \u0394 Negative Appeals",
       subtitle = "Controlled for Standing in Polls, Ideological Extremity and Issue Ownership" ) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position="bottom",
        legend.title = element_blank()) +
  scale_color_viridis_d() +
  geom_hline(yintercept = 0, size = .2, linetype = "dashed") +
  guides(color=guide_legend(nrow=3,byrow=TRUE))
```

```{r "h2"}
df <- df %>%
  mutate(group1 = ifelse(ji1<=.2, 0,
                  ifelse(ji1>.2 & ji1<=.5, 1, 2)),
         group2 = ifelse(ji2<=.5, 0,
                  ifelse(ji2>.5 & ji2<=3, 1, 2)),
         group3 = ifelse(ji3<=.5, 0,
                  ifelse(ji3>.5 & ji3<=3, 1, 2)))

#Do for each group
h2_1 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9"),
                      controls = c("ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8",
                                  "io1","io2","io3","io4"),
                      model = "glmer_mv",
                  subsets = list(group1 = unique(df$group1)))

h2_2 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9"),
                      controls = c("ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8",
                                  "io1","io2","io3","io4"),
                      model = "glmer_mv",
                  subsets = list(group1 = unique(df$group2)))

h2_3 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9"),
                      controls = c("ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8",
                                  "io1","io2","io3","io4"),
                      model = "glmer_mv",
                  subsets = list(group1 = unique(df$group3)))

h2_1 <- h2_1 %>% mutate(id = "ji1")
h2_2 <- h2_2 %>% mutate(id = "ji2")
h2_3 <- h2_3 %>% mutate(id = "ji3")

h2 <- h2_1 %>% add_row(h2_2) %>% add_row(h2_3)

h3_1 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8"),
                      controls = c("ji1", "ji2", "ji3",
                                   "polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9",
                                  "io1","io2","io3","io4"),
                      model = "glmer_mv") #MAKE GROUPS

h4 <- run_specs(df = df,
                      y = c("negative_appeals"),
                      x = c("io1","io2","io3","io4"),
                      controls = c("ji1", "ji2", "ji3",
                                   "polls1","polls2","polls3","polls4",
                                  "polls5","polls6","polls7","polls8",
                                  "polls9",
                                  "ie1","ie2","ie3","ie4","ie5","ie6",
                                  "ie7","ie8"),
                      model = "glmer_mv",
                     subsets = list(group1 = unique(df$group1))) 

```


